function save(){
    error=false;
    try{a=app.activeDocument.fullName;}catch(e){alert('No Active Document, or document has not yet been saved.');error=true};
    if (!error){
        b=new File(a);
        
        d=dialog();         

        c=b.name.slice(0,-4)+'_diffuse.jpg';
        isolate('diffuse');
        jpg100();
        isolate('diffuse');
        
        c=b.name.slice(0,-4)+'_transparency.jpg';
        isolate('transparency');
        jpg100();
        isolate('transparency');
        
        d.hide();
        app.beep();
    }
}
try{save()}catch(err){alert(err)}

function dialog(){
    w = new Window ("palette", undefined, undefined, {borderless: true});
    w.add ("statictext", undefined, "Exporting. Please wait...");
    w.show()
    return w
}

function isolate(name){
// =======================================================
var idslct = charIDToTypeID( "slct" );
    var desc15 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref10 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        ref10.putName( idLyr, name );
    desc15.putReference( idnull, ref10 );
    var idMkVs = charIDToTypeID( "MkVs" );
    desc15.putBoolean( idMkVs, false );
executeAction( idslct, desc15, DialogModes.NO );
// =======================================================
var idShw = charIDToTypeID( "Shw " );
    var desc16 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var list2 = new ActionList();
            var ref11 = new ActionReference();
            var idLyr = charIDToTypeID( "Lyr " );
            var idOrdn = charIDToTypeID( "Ordn" );
            var idTrgt = charIDToTypeID( "Trgt" );
            ref11.putEnumerated( idLyr, idOrdn, idTrgt );
        list2.putReference( ref11 );
    desc16.putList( idnull, list2 );
    var idTglO = charIDToTypeID( "TglO" );
    desc16.putBoolean( idTglO, true );
executeAction( idShw, desc16, DialogModes.NO );    
}

function jpg100(){
var idExpr = charIDToTypeID( "Expr" );
    var desc26 = new ActionDescriptor();
    var idUsng = charIDToTypeID( "Usng" );
        var desc27 = new ActionDescriptor();
        var idOp = charIDToTypeID( "Op  " );
        var idSWOp = charIDToTypeID( "SWOp" );
        var idOpSa = charIDToTypeID( "OpSa" );
        desc27.putEnumerated( idOp, idSWOp, idOpSa );
        var idDIDr = charIDToTypeID( "DIDr" );
        desc27.putBoolean( idDIDr, true );
        var idIn = charIDToTypeID( "In  " );
        //Output path
        desc27.putPath( idIn, new File( b.parent.absoluteURI ) );
        var idovFN = charIDToTypeID( "ovFN" );
        //Change file name here
        desc27.putString( idovFN, c );
        var idFmt = charIDToTypeID( "Fmt " );
        var idIRFm = charIDToTypeID( "IRFm" );
        var idJPEG = charIDToTypeID( "JPEG" );
        desc27.putEnumerated( idFmt, idIRFm, idJPEG );
        var idIntr = charIDToTypeID( "Intr" );
        desc27.putBoolean( idIntr, false );
        var idQlty = charIDToTypeID( "Qlty" );
        desc27.putInteger( idQlty, 100 );
        var idQChS = charIDToTypeID( "QChS" );
        desc27.putInteger( idQChS, 0 );
        var idQCUI = charIDToTypeID( "QCUI" );
        desc27.putInteger( idQCUI, 0 );
        var idQChT = charIDToTypeID( "QChT" );
        desc27.putBoolean( idQChT, false );
        var idQChV = charIDToTypeID( "QChV" );
        desc27.putBoolean( idQChV, false );
        var idOptm = charIDToTypeID( "Optm" );
        desc27.putBoolean( idOptm, true );
        var idPass = charIDToTypeID( "Pass" );
        desc27.putInteger( idPass, 1 );
        var idblur = charIDToTypeID( "blur" );
        desc27.putDouble( idblur, 0.000000 );
        var idMtt = charIDToTypeID( "Mtt " );
        desc27.putBoolean( idMtt, true );
        var idEICC = charIDToTypeID( "EICC" );
        desc27.putBoolean( idEICC, false );
        var idMttR = charIDToTypeID( "MttR" );
        desc27.putInteger( idMttR, 255 );
        var idMttG = charIDToTypeID( "MttG" );
        desc27.putInteger( idMttG, 255 );
        var idMttB = charIDToTypeID( "MttB" );
        desc27.putInteger( idMttB, 255 );
        var idSHTM = charIDToTypeID( "SHTM" );
        desc27.putBoolean( idSHTM, false );
        var idSImg = charIDToTypeID( "SImg" );
        desc27.putBoolean( idSImg, true );
        var idSWsl = charIDToTypeID( "SWsl" );
        var idSTsl = charIDToTypeID( "STsl" );
        var idSLAl = charIDToTypeID( "SLAl" );
        desc27.putEnumerated( idSWsl, idSTsl, idSLAl );
        var idSWch = charIDToTypeID( "SWch" );
        var idSTch = charIDToTypeID( "STch" );
        var idCHsR = charIDToTypeID( "CHsR" );
        desc27.putEnumerated( idSWch, idSTch, idCHsR );
        var idSWmd = charIDToTypeID( "SWmd" );
        var idSTmd = charIDToTypeID( "STmd" );
        var idMDCC = charIDToTypeID( "MDCC" );
        desc27.putEnumerated( idSWmd, idSTmd, idMDCC );
        var idohXH = charIDToTypeID( "ohXH" );
        desc27.putBoolean( idohXH, false );
        var idohIC = charIDToTypeID( "ohIC" );
        desc27.putBoolean( idohIC, true );
        var idohAA = charIDToTypeID( "ohAA" );
        desc27.putBoolean( idohAA, true );
        var idohQA = charIDToTypeID( "ohQA" );
        desc27.putBoolean( idohQA, true );
        var idohCA = charIDToTypeID( "ohCA" );
        desc27.putBoolean( idohCA, false );
        var idohIZ = charIDToTypeID( "ohIZ" );
        desc27.putBoolean( idohIZ, true );
        var idohTC = charIDToTypeID( "ohTC" );
        var idSToc = charIDToTypeID( "SToc" );
        var idOCzerothree = charIDToTypeID( "OC03" );
        desc27.putEnumerated( idohTC, idSToc, idOCzerothree );
        var idohAC = charIDToTypeID( "ohAC" );
        var idSToc = charIDToTypeID( "SToc" );
        var idOCzerothree = charIDToTypeID( "OC03" );
        desc27.putEnumerated( idohAC, idSToc, idOCzerothree );
        var idohIn = charIDToTypeID( "ohIn" );
        desc27.putInteger( idohIn, -1 );
        var idohLE = charIDToTypeID( "ohLE" );
        var idSTle = charIDToTypeID( "STle" );
        var idLEzerothree = charIDToTypeID( "LE03" );
        desc27.putEnumerated( idohLE, idSTle, idLEzerothree );
        var idohEn = charIDToTypeID( "ohEn" );
        var idSTen = charIDToTypeID( "STen" );
        var idENzerozero = charIDToTypeID( "EN00" );
        desc27.putEnumerated( idohEn, idSTen, idENzerozero );
        var idolCS = charIDToTypeID( "olCS" );
        desc27.putBoolean( idolCS, false );
        var idolEC = charIDToTypeID( "olEC" );
        var idSTst = charIDToTypeID( "STst" );
        var idSTzerozero = charIDToTypeID( "ST00" );
        desc27.putEnumerated( idolEC, idSTst, idSTzerozero );
        var idolWH = charIDToTypeID( "olWH" );
        var idSTwh = charIDToTypeID( "STwh" );
        var idWHzeroone = charIDToTypeID( "WH01" );
        desc27.putEnumerated( idolWH, idSTwh, idWHzeroone );
        var idolSV = charIDToTypeID( "olSV" );
        var idSTsp = charIDToTypeID( "STsp" );
        var idSPzerofour = charIDToTypeID( "SP04" );
        desc27.putEnumerated( idolSV, idSTsp, idSPzerofour );
        var idolSH = charIDToTypeID( "olSH" );
        var idSTsp = charIDToTypeID( "STsp" );
        var idSPzerofour = charIDToTypeID( "SP04" );
        desc27.putEnumerated( idolSH, idSTsp, idSPzerofour );
        var idolNC = charIDToTypeID( "olNC" );
            var list3 = new ActionList();
                var desc28 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzerozero = charIDToTypeID( "NC00" );
                desc28.putEnumerated( idncTp, idSTnc, idNCzerozero );
            var idSCnc = charIDToTypeID( "SCnc" );
            list3.putObject( idSCnc, desc28 );
                var desc29 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNConenine = charIDToTypeID( "NC19" );
                desc29.putEnumerated( idncTp, idSTnc, idNConenine );
            var idSCnc = charIDToTypeID( "SCnc" );
            list3.putObject( idSCnc, desc29 );
                var desc30 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwoeight = charIDToTypeID( "NC28" );
                desc30.putEnumerated( idncTp, idSTnc, idNCtwoeight );
            var idSCnc = charIDToTypeID( "SCnc" );
            list3.putObject( idSCnc, desc30 );
                var desc31 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc31.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list3.putObject( idSCnc, desc31 );
                var desc32 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc32.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list3.putObject( idSCnc, desc32 );
                var desc33 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc33.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list3.putObject( idSCnc, desc33 );
        desc27.putList( idolNC, list3 );
        var idobIA = charIDToTypeID( "obIA" );
        desc27.putBoolean( idobIA, false );
        var idobIP = charIDToTypeID( "obIP" );
        desc27.putString( idobIP, """""" );
        var idobCS = charIDToTypeID( "obCS" );
        var idSTcs = charIDToTypeID( "STcs" );
        var idCSzeroone = charIDToTypeID( "CS01" );
        desc27.putEnumerated( idobCS, idSTcs, idCSzeroone );
        var idovNC = charIDToTypeID( "ovNC" );
            var list4 = new ActionList();
                var desc34 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzeroone = charIDToTypeID( "NC01" );
                desc34.putEnumerated( idncTp, idSTnc, idNCzeroone );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc34 );
                var desc35 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwozero = charIDToTypeID( "NC20" );
                desc35.putEnumerated( idncTp, idSTnc, idNCtwozero );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc35 );
                var desc36 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzerotwo = charIDToTypeID( "NC02" );
                desc36.putEnumerated( idncTp, idSTnc, idNCzerotwo );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc36 );
                var desc37 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNConenine = charIDToTypeID( "NC19" );
                desc37.putEnumerated( idncTp, idSTnc, idNConenine );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc37 );
                var desc38 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCzerosix = charIDToTypeID( "NC06" );
                desc38.putEnumerated( idncTp, idSTnc, idNCzerosix );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc38 );
                var desc39 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc39.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc39 );
                var desc40 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc40.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc40 );
                var desc41 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwofour = charIDToTypeID( "NC24" );
                desc41.putEnumerated( idncTp, idSTnc, idNCtwofour );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc41 );
                var desc42 = new ActionDescriptor();
                var idncTp = charIDToTypeID( "ncTp" );
                var idSTnc = charIDToTypeID( "STnc" );
                var idNCtwotwo = charIDToTypeID( "NC22" );
                desc42.putEnumerated( idncTp, idSTnc, idNCtwotwo );
            var idSCnc = charIDToTypeID( "SCnc" );
            list4.putObject( idSCnc, desc42 );
        desc27.putList( idovNC, list4 );
        var idovCM = charIDToTypeID( "ovCM" );
        desc27.putBoolean( idovCM, false );
        var idovCW = charIDToTypeID( "ovCW" );
        desc27.putBoolean( idovCW, true );
        var idovCU = charIDToTypeID( "ovCU" );
        desc27.putBoolean( idovCU, true );
        var idovSF = charIDToTypeID( "ovSF" );
        desc27.putBoolean( idovSF, true );
        var idovCB = charIDToTypeID( "ovCB" );
        desc27.putBoolean( idovCB, true );
        var idovSN = charIDToTypeID( "ovSN" );
        desc27.putString( idovSN, """images""" );
    var idSaveForWeb = stringIDToTypeID( "SaveForWeb" );
    desc26.putObject( idUsng, idSaveForWeb, desc27 );
executeAction( idExpr, desc26, DialogModes.NO );
}